In [1]:
import numpy as np

In [2]:
escalar = 5.76
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[4,6],[7,9]])
tensor = np.array([ 
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]] 
])

In [4]:
vectorT = vector.T
print(vectorT)

[3 4 5 6]


In [7]:
matrizT = matriz.T
print(matrizT)
print(matriz.shape)
print(matrizT.shape)

[[1 4 7]
 [2 6 9]]
(3, 2)
(2, 3)


In [9]:
tensor_T = tensor.T
print(tensor.T)
print("____________")
print(tensor)

[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]
____________
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [11]:
matriz_t_t = matrizT.T
print(matriz_t_t)

[[1 2]
 [4 6]
 [7 9]]


In [15]:
A = np.array([[1,2],[3,4],[5,6]])
B = matriz
C = A + B
print(C)

[[ 2  4]
 [ 7 10]
 [12 15]]


In [16]:
D = matriz + escalar
D

array([[ 6.76,  7.76],
       [ 9.76, 11.76],
       [12.76, 14.76]])

In [18]:
matriz5 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
matriz5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
matriz5_t= matriz5.T
matriz5_t

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

### Suma de matrices, diferentes dimensiones

In [25]:
vector = np.array([3,4,5])
matriz = np.array([[1,2],[4,6],[7,9]])
suma = vector + matriz.T
print(matriz)
suma

[[1 2]
 [4 6]
 [7 9]]


array([[ 4,  8, 12],
       [ 5, 10, 14]])